spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: 123456789

  jpa:
    open-in-view: false

server:
  port: 8585